import { Hono } from 'hono';
import { getProfile } from '../db/repo.js';
import { runDailySummaryForUser, regenerateProfileForUser } from '../cron/jobs.js';
import { regenerateSchema, safeParse } from '../validation.js';

export const profileRoutes = new Hono<{ Variables: { user_id: string } }>();

/**
 * GET /api/profile
 * Returns the latest user profile (Markdown).
 */
profileRoutes.get('/', (c) => {
  const user_id = c.get('user_id');
  const profile = getProfile(user_id);
  if (!profile) {
    return c.json({ profile: null, message: 'No profile yet. Will be generated by next cron run.' });
  }
  return c.json(profile);
});

/**
 * POST /api/profile/regenerate
 * Manual trigger for the *current user's* profile regeneration (debug/dev).
 * Scoped to the authenticated user — never touches other users' data.
 * Body: { scope: 'daily' | 'weekly' }
 */
profileRoutes.post('/regenerate', async (c) => {
  const user_id = c.get('user_id');
  const body = await c.req.json().catch(() => ({}));
  const parsed = safeParse(regenerateSchema, body);
  if (!parsed.ok) return c.json({ error: parsed.error }, 400);
  const scope = parsed.data.scope;
  const date = parsed.data.date;

  // Fire-and-forget so the request returns immediately.
  if (scope === 'daily') {
    runDailySummaryForUser(user_id, date).catch(e => console.error('manual daily failed', e));
  } else {
    regenerateProfileForUser(user_id, 'manual').catch(e => console.error('manual weekly failed', e));
  }
  return c.json({ triggered: scope, user_id, date: date ?? 'yesterday', note: 'running in background' });
});
