import { Hono } from 'hono';
import { getProfile } from '../db/repo.js';
import { runDailySummary, runWeeklyProfile } from '../cron/jobs.js';

export const profileRoutes = new Hono<{ Variables: { user_id: string } }>();

/**
 * GET /api/profile
 * Returns the latest user profile (Markdown).
 */
profileRoutes.get('/', (c) => {
  const user_id = c.get('user_id');
  const profile = getProfile(user_id);
  if (!profile) {
    return c.json({ profile: null, message: 'No profile yet. Will be generated by next cron run.' });
  }
  return c.json(profile);
});

/**
 * POST /api/profile/regenerate
 * Manual trigger for profile regeneration (debug/dev).
 * Body: { scope: 'daily' | 'weekly' }
 */
profileRoutes.post('/regenerate', async (c) => {
  const body = await c.req.json().catch(() => ({})) as any;
  const scope = body.scope ?? 'weekly';

  if (scope === 'daily') {
    runDailySummary().catch(e => console.error('manual daily failed', e));
    return c.json({ triggered: 'daily', note: 'running in background' });
  } else {
    runWeeklyProfile().catch(e => console.error('manual weekly failed', e));
    return c.json({ triggered: 'weekly', note: 'running in background' });
  }
});
